### ISSUE TITLE
✨ Feature - Login V2

### ISSUE THREAD

**Issue by fegma59** [uni-clouds/unicloud-frontwebapp#117]
Post na rota: /indetify/
payload: {username: username}

Success Response:
```
{
    "logo": "https://brokermediastorage.blob.core.windows.net/devmedia/Uni.Cloud/collision_TM0ZaPj.png",
    "authentication_factors": "['password']"
}
```

Error Response:
```
{
    "data": {
        "detail": "No active account found or incorrect password with the given credentials",
        "code": "login_failed",
        "messages": [
            {
                "token_class": "AccessToken",
                "token_type": "access",
                "message": "No active account found or incorrect password with the given credentials"
            }
        ]
    }
}
```

Post para a rota: /login-v2/
payload: {username: username, password: password}

Success Response:
```
{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2MDY3NTI5NiwiaWF0IjoxNjU5Mzc5Mjk2LCJqdGkiOiI3MmI3OTgwMDU0OWQ0MWU2YmQxNTAyNTIxYzlmZTJiOSIsInVzZXJfaWQiOjF9.5n1BAw7_ih6e51KNb0O-C7HZrhNOhBKe9x4bfh893z8",
    "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU5MzgyODk2LCJpYXQiOjE2NTkzNzkyOTYsImp0aSI6IjE4MGRkNWY3MmRkZTQ5NjliYWMzMmE2OTllMzE4MzVmIiwidXNlcl9pZCI6MX0.IL9sAfN080ZFuNtSkFyg7HF7Jb2-ue2V9U8943rl7Zk"
}
```

Error Response:
```
{
    "data": {
        "detail": "No active account found or incorrect password with the given credentials",
        "code": "login_failed",
        "messages": [
            {
                "token_class": "AccessToken",
                "token_type": "access",
                "message": "No active account found or incorrect password with the given credentials"
            }
        ]
    }
}
```

**Comment by ManuCoutinho** [comment]
Refatorar tela de login:
Criar novo design em dois passos:

bicolunada
mensagem de boas vinda animada
input email ou form login
seleção de idioma

**Comment by ManuCoutinho** [comment]
### primeiro acesso:

- [ ]  solicitar o e-mail ao usuário
    - [ ]  salvar o e-mail num *state* ou *store* e identificar o e-mail do usuário na rota `/indetify/`
        - [ ]  caso seja inválido, exibir mensagem de *bad news* 😈
        - [ ]  caso seja válido, renderizar a segunda tela solicitando:
            - [ ]  senha (campo obrigatório)
            - [ ]  idioma de preferência
                - [ ]  caso seja setado idioma, realizar o post em paralelo ao login
                - [ ]  setar manualmente na sessão atual o `locale=idiomaSelecionado`
                - [ ]  caso não seja enviado idioma:
                    - [ ]  verificar se o  🍪  `NEXT_LOCALE` existe no browser e deletar
        - [ ]  post para rota `/login-v2/` utilizando o e-mail salvo no state e a senha solicitada
            - [ ]  caso o login seja mal sucedido, exibir mensagem de *bad news* 😈
            - [ ]  caso o login seja bem sucedido, redirecionar o usuário `route.push(🏡)`

---

### usuário não logado e/ou re-autenticação:

- [ ]  identificar se já tem cookies com `username` e `theme` setados e carregar
    - [ ]  setar mensagem de boas vindas de volta ao usuário e solicitar senha
    - [ ]  realizar autenticação com:
        - [ ]  carregamento das preferências de UI
        - [ ]  redirecionamento para rota 🏡
- [ ]  incluir botão e/ou link para alterar o e-mail, caso o usuário deseje logar com outra conta

---

**Comment by ManuCoutinho** [comment]
Em ajustes de acordo com a revisão

**Comment by ManuCoutinho** [comment]
Aguardando ajustes do backend
Issues
https://github.com/uni-clouds/back-unicloud/issues/184
https://github.com/uni-clouds/back-unicloud/issues/185
