### ISSUE TITLE
✨FEAT - User preferences

### ISSUE THREAD

**Issue by joaolavelino** [uni-clouds/unicloud-frontwebapp#120]
Criar seção de preferências de usuário dentro da página de user profile.

### Features
 - Troca de idiomas
 - Temas de cores
---

### Rota GET
Payload:
 - 'language' : "pt"|"en"|"fr"|"es" (trazer do i18n)
 - 'theme': "dark"|"light"
---

### Rota POST
Pode ser feita enviando ambos os parâmetros ou um apenas um deles

**Comment by ManuCoutinho** [comment]
- [ ] Refatorar NavHeader/Dropdown
  - nova estrutura de menu _vide abaixo_
- [ ] Remover select idioma do footer
- [ ] Criar navegação interna com o `<NavigationTabs/>`
- [ ] Criar rota /activity/
- [ ] Transferir informações de login para a rota /activity/
- [ ] Criar nova estrutura de layout da tela de user preferences
- [ ] Criar componente de seleção de tema
- [ ] Criar componente de seleção de idioma
- [ ] Criar componente Divider

#### Nova estrutura de menu

- Perfil
- Configurações
  - tela
  - segurança
  - notificações 
- Notificações
- Atividades
- Logout
