### ISSUE TITLE
♻ Upkeep Menu

### ISSUE THREAD

**Issue by fegma59** [uni-clouds/unicloud-frontwebapp#250]

**Comment by fegma59** [comment]
Precisamos começar a organizar nosso menu em módulos, para acomodar de forma mais clean e organizada vários novos botões que estão por vir.

No momento, precisamos de:

- Infra Root (exclusivo do root)
    Pods
    Resources
    Monitoring

- Financeiro
    Contracts

- Sales
    Partner/Customers (Root/Partner)
    Registro de Oportunidades
    Calculadora

- Ambiente Cloud
    Projetos
    VPCs
    Edge Networks
    Policy Groups
    Elastic IPs

- Compute
    Instancias

- Storage
    Object Storage

**Comment by ManuCoutinho** [comment]
UI/UX refs
https://dribbble.com/shots/16271760-Sidebar-navigation-for-Dashboard


![Image](https://user-images.githubusercontent.com/80268705/187761447-0a298493-daf2-48c6-9f13-77b747c6c068.jpg)
