### ISSUE TITLE
CALC_SETTINGS - Medidas de Custeio

### ISSUE THREAD

**Issue by joaolavelino** [uni-clouds/unicloud-frontwebapp#264]
Seguindo a estrutura do gerenciamento de planos de subscription, criar a feature de gerenciamento de medidas de custeio.

# Criar página da rota principal
Construção da página Calculator - Mesmo que tenha apenas um placeholder, e o botão de settings

# Variáveis:
### value: a quantidade de unidades desta medida.

# CRUD:
### GET: Pegar a lista com as unidades de medida existentes no BD,
`[  { name: string  ,  value: number  ,  id:  number }  ]`

### POST: Enviar uma unidade de medida para o BD,
`[  { name: string  ,  value: number   }  ]`

### PATCH: Fazer o update de unidade de medida,
`[  { name?: string  ,  value?: number  ,  id:  number }  ]`

### DELETE: Fazer o update de unidade de medida,
`[  {  id:  number }  ]`

**Comment by fegma59** [comment]
```
POST http://127.0.0.1:8000/root/measures/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "name": "Gigabyte",
    "code": "GB"
}

###
GET http://127.0.0.1:8000/root/measures/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
}

###

DELETE http://127.0.0.1:8000/root/measures/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "measure_id": 1
}
```
