### ISSUE TITLE
CALC_SETTINGS - Currency

### ISSUE THREAD

**Issue by joaolavelino** [uni-clouds/unicloud-frontwebapp#267]
Seguindo a estrutura do gerenciamento de planos de subscription, criar a feature de gerenciamento de parâmetros de moeda.

# CRUD:
### GET: Receber os parâmetros de moeda em um objeto com: PTAX, Dolar Unicloud, Margem de segurança.
`[  { ptax: number  ,  unicloud_dollar: number  ,  safety_margin:  number }  ]`

### PATCH: Fazer o update de algum parâmetro,
`[  { unicloud_dollar?: number  ,  safety_margin?: number  }  ]`

**Comment by fegma59** [comment]
BackEnd Endpoints:

`POST http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "currency": "usd",
    "unicloud_dollar": 5.50,
    "safety_margin": 15
}

###

GET http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
}
###

DELETE http://127.0.0.1:8000/root/currency/ HTTP/1.1
content-type: application/json
Authorization: Bearer Token

{
    "currency_id": 3
}`
