### ISSUE TITLE
Feature Add Users

### ISSUE THREAD

**Issue by fegma59** [uni-clouds/unicloud-frontwebapp#28]
Rota:
invite-user/

Metodo:
Post

Payload:
{email: email}

Ao ir em "Users", e clicar em "Adicionar Usuário", o fluxo é enviar um convite ao usuário para ele se registrar e ingressar na plataforma do cliente.
Para isso, basta solicitar o e-mail do novo usuário a ser convidado e enviar para a rota acima. 
O back-end enviará um e-mail de boas vindas para o usuário convidado. Neste e-mail terá uma URL com um Token de validação do convite. Está Hardcoded no Back da seguinte forma:
'https://broker.uni.cloud/auth-register/?token={token}'

Quando o usuário clicar no link do convite, o browser fará um get na rota do Front End na rota '/auth-register/' passando o token de validação do convite na query string.
O Front precisa fazer uma query para validar o token no back:

Rota:
check-token/

Metodo: 
Post

Payload:
{token: token}

Se o token for valido, o back retornará o objeto:
{'id':token_data.id, 'token':token_data.token, 'email':token_data.email, 'razao_social':token_data.customer.razao_social, 'is_valid':True}

Se o Token não for válido, o back retornará para o front:
{'is_valid':False}

Se o token for válido, deve então renderizar o formulário de registro do novo usuário convidado e enviar ao BackEnd:

Rota:
/users/

Metodo:
Post

Payload:
{username:username, password: password, first_name:first_name, last_name: last name, phone: phone, address: address, city city, state: state, country: country}

Após isso, o convite é deletado, e ele passa a se tornar um usuário de fato.

A tela Usuários, deve conter duas listas, a primeira e de mais destaque, é a tela de usuários. 
A segunda, é a tela de convidados, que está aguardando o usuário se registrar para se tornar um usuário.

Para obter as listas:

Rota:
/users/

Metodo:
Get

Rota:
/invite-user/

Metodo:
Get

**Comment by ManuCoutinho** [comment]
/update-invitation/ 

Metodo: 
Patch

Payload: 
{id: id} É o ID do convite que voce tem no Front no objeto da listagem de convites.
