### ISSUE TITLE
Refactor visual da tela de Login

### ISSUE THREAD

**Issue by fegma59** [uni-clouds/unicloud-frontwebapp#41]
Na tela de login existe a informação:

Ainda não possui acesso?[Contate nossa equipe](https://broker.uni.cloud/#)

OU
[Comercial](https://broker.uni.cloud/commercial)
[Suporte Técnico](https://broker.uni.cloud/help-desk)

Tirar o link do "ainda não possui acesso?"

Mudar para:

Ainda não possui acesso?

Comercial (Link) OU Suporte (Link)

**Comment by ManuCoutinho** [comment]
Temos algo para colocar no link do comercial ou suporte. Nem um e-mail temporário?
