### ISSUE TITLE
♻ upkeep multilanguage

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/unicloud-frontwebapp#54]
- Incluir script para setar o idioma default com base nas pref. do usuário utilizando a `navigator.language`
- Incluir script para alterar a tag `lang={value do idioma escolhido}`, no momento da escolha pelo usuário

**Comment by joaolavelino** [comment]
Ola manu.. O idioma de base já está sendo setado com o i18n.

- O i18n já tem essa detecção do idioma pelo navegador. Eu coloquei essa função no o último commit do multilanguages.
- Assim que puder começar a task, eu já posso ver isso certinho.

**Comment by ManuCoutinho** [comment]
aproved by #61
