### ISSUE TITLE
♻ REFACTOR:  TABELAS

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/unicloud-frontwebapp#65]
TABELAS
-alterar tamanho da fonte responsiva: deve reduzir em 'md' e 'sm'
- não permitir selecionar mais de um item da tabela - retirar os checkboxs, passar a selecionar o item pelo clique na row, que deverá utilizar o id para identificá-la.
- Retirar o selectAll sem quebrar a função de sort
  - ícone de details no final da row com tooltip 
  - verificar uma solução para o mobile
- Rever o campo inativo/ativo - não está mudando de cor.  Motivo: A lógica ternária da tradução deve ficar dentro da célula (TableCell) e não na criação das rows.
     - Exibição dos detalhes -> substituir o componente tableToolBar e colocar o acesso para os detalhes (junto com o toggle de ativo e inativo) em um ícone no final da tabela
       - A table toolbar irá renderizar uma searchbar   
       - Fixar tamanho dos ícones nos idiomas mais verbosos

**Comment by ManuCoutinho** [comment]
**reportar quaisquer feat ou erros que aparecerem ao longo da taskt

**Comment by joaolavelino** [comment]
19/7 - Progresso

- [ ]  alterar tamanho da fonte responsiva: deve reduzir em 'md' e 'sm'

- [ ] - não permitir selecionar mais de um item da tabela - retirar os checkboxs, passar a selecionar o item pelo clique na row, que deverá utilizar o id para identificá-la.

- [ ] Retirar o selectAll sem quebrar a função de sort (AINDA ESTÁ DANDO O ERRO DE APARECER MAIS CLIENTES)

- [ ] ícone de details no final da row com tooltip

- [ ] verificar uma solução para o mobile

- [ ] Rever o campo inativo/ativo - não está mudando de cor. Motivo: A lógica ternária da tradução deve ficar dentro da célula (TableCell) e não na criação das rows.

- [ ] Exibição dos detalhes -> substituir o componente tableToolBar e colocar o acesso para os detalhes (junto com o toggle de ativo e inativo) em um ícone no final da tabela

- [ ] A table toolbar irá renderizar uma searchbar

- [ ] Fixar tamanho dos ícones nos idiomas mais verbosos

**Comment by joaolavelino** [comment]
20/7 - Progresso - Tabela de Customers (uma vez finalizando essa, fica rapido apenas aplicar as alterações nos Users / Invites)

- [ ]  alterar tamanho da fonte responsiva: deve reduzir em 'md' e 'sm'

- [x] - não permitir selecionar mais de um item da tabela - retirar os checkboxs, passar a selecionar o item pelo clique na row, que deverá utilizar o id para identificá-la.

- [x] Retirar o selectAll sem quebrar a função de sort (AINDA ESTÁ DANDO O ERRO DE APARECER MAIS CLIENTES)

- [x] ícone de details no final da row com tooltip

- [ ] verificar uma solução para o mobile

- [x] Rever o campo inativo/ativo - não está mudando de cor. Motivo: A lógica ternária da tradução deve ficar dentro da célula (TableCell) e não na criação das rows.

- [x] Exibição dos detalhes -> substituir o componente tableToolBar e colocar o acesso para os detalhes (junto com o toggle de ativo e inativo) em um ícone no final da tabela **icone ativo e inativo para uma proxima task**

- [x] A table toolbar irá renderizar uma searchbar

- [ ] Fixar tamanho dos ícones nos idiomas mais verbosos

**Comment by joaolavelino** [comment]
Enviado PR #93
