### ISSUE TITLE
♻ REFACTOR: Multilanguage

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/unicloud-frontwebapp#72]
MULTILANGUAGE
- bug - Headers das tabelas não atualizam
- bug - VERIFICAR COMO CARREGAMENTO INICIAL DO IDIOMA - não carrega idioma normal
- Mudar as cidades no location dos PODS (MADRID & PARIS)
- Mover component para separar a parte visual da lógica
- Parte visual em Elements e outra pasta do component

**Comment by joaolavelino** [comment]
- Modificar a localização das tags de traduçao de status da tabela. (ao invés de colocar os tags direto na função, colocar no campo diretamente)
- Modificar os tags dos cards do Dashboard para não rolar conflito com os ícones

**Comment by ManuCoutinho** [comment]
Issue has been resolved across PR#80
