### ISSUE TITLE
♻ REFACTOR: botões não funcionais

### ISSUE THREAD

**Issue by ManuCoutinho** [uni-clouds/unicloud-frontwebapp#73]
Remover todos os botões não funcionais.

- Retirar o botão de reports no Dashboard
- No rodapé :
   - Solicitar os arquivos para Termos e politicas (*Como não temos o mateiral ainda, deixar os links inativos/invisíveis)
   - criar content para o help-desk
   - 
- exportar dados da tabela?

**Comment by joaolavelino** [comment]
Página do notion com as FAQ.
https://www.notion.so/joaoavelino/Uni-Cloud-FAQ-Help-desk-114fb027eb904ce29c5b6b3942a59192

**Comment by joaolavelino** [comment]
PR #90

**Comment by ManuCoutinho** [comment]
Merge realizado
